package: twoeg
version: '0.3-alpha'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/twoeg

page:
    title: translate:navigation
    perm: admin
    subpages:
        readme: { title: translate:readme }
        documentation: { title: translate:documentation }
        changelog: { title: translate:changelog }

requires:
    redaxo: '>=5.0.0-beta2'