package: twoeg
version: '0.1'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/twoeg

page:
    title: translate:navigation
    perm: admin
    subpages:
        readme: { title: translate:readme }

requires:
    redaxo: '>=5.0.0-beta2'